from __future__ import annotations

MODEL_REGISTRY: dict[str, dict[str, object]] = {
    "distilbert-base-uncased_textcls": {
        "hf_model_id": "distilbert-base-uncased",
        "task_key": "text_classification",
        "pipeline_tag": "text-classification",
        "family": "bert",
        "modality": "text",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["glue_sst2", "ag_news", "imdb"],
        "loader_template": "hf_sequence_classification",
        "explainability": {
            "supported": True,
            "preferred_methods": ["integrated_gradients", "attention_rollout"],
            "target_type": "class_label",
            "input_type": "single_text",
            "attribution_level": "token",
            "requires_gradients": True,
            "requires_attention": True,
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": True,
        },
    },
    "roberta-base_textcls": {
        "hf_model_id": "roberta-base",
        "task_key": "text_classification",
        "pipeline_tag": "text-classification",
        "family": "roberta",
        "modality": "text",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["ag_news", "imdb"],
        "loader_template": "hf_sequence_classification",
        "explainability": {
            "supported": True,
            "preferred_methods": ["integrated_gradients", "attention_rollout"],
            "target_type": "class_label",
            "input_type": "single_text",
            "attribution_level": "token",
            "requires_gradients": True,
            "requires_attention": True,
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": True,
        },
    },
    "bert-base-uncased_textcls": {
        "hf_model_id": "bert-base-uncased",
        "task_key": "text_classification",
        "pipeline_tag": "text-classification",
        "family": "bert",
        "modality": "text",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["glue_sst2", "ag_news"],
        "loader_template": "hf_sequence_classification",
        "explainability": {
            "supported": True,
            "preferred_methods": ["integrated_gradients", "attention_rollout"],
            "target_type": "class_label",
            "input_type": "single_text",
            "attribution_level": "token",
            "requires_gradients": True,
            "requires_attention": True,
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": True,
        },
    },
    "bert-base-cased_tokencls": {
        "hf_model_id": "bert-base-cased",
        "task_key": "token_classification",
        "pipeline_tag": "token-classification",
        "family": "bert",
        "modality": "text",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["conll2003", "wnut_17"],
        "loader_template": "hf_token_classification",
        "explainability": {
            "supported": True,
            "preferred_methods": ["integrated_gradients", "attention_rollout"],
            "target_type": "token_label",
            "input_type": "token_sequence",
            "attribution_level": "token",
            "requires_gradients": True,
            "requires_attention": True,
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": True,
        },
    },
    "distilbert-base-cased_tokencls": {
        "hf_model_id": "distilbert-base-cased",
        "task_key": "token_classification",
        "pipeline_tag": "token-classification",
        "family": "distilbert",
        "modality": "text",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["conll2003"],
        "loader_template": "hf_token_classification",
        "explainability": {
            "supported": True,
            "preferred_methods": ["integrated_gradients", "attention_rollout"],
            "target_type": "token_label",
            "input_type": "token_sequence",
            "attribution_level": "token",
            "requires_gradients": True,
            "requires_attention": True,
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": True,
        },
    },
    "distilbert-base-uncased_tokencls": {
        "hf_model_id": "distilbert-base-uncased",
        "task_key": "token_classification",
        "pipeline_tag": "token-classification",
        "family": "distilbert",
        "modality": "text",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["wnut_17"],
        "loader_template": "hf_token_classification",
        "explainability": {
            "supported": True,
            "preferred_methods": ["integrated_gradients", "attention_rollout"],
            "target_type": "token_label",
            "input_type": "token_sequence",
            "attribution_level": "token",
            "requires_gradients": True,
            "requires_attention": True,
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": True,
        },
    },
    "distilbert-base-uncased_similarity": {
        "hf_model_id": "distilbert-base-uncased",
        "task_key": "sentence_similarity",
        "pipeline_tag": "sentence-similarity",
        "family": "distilbert",
        "modality": "text",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["glue_stsb", "glue_mrpc"],
        "loader_template": "hf_sentence_similarity",
        "explainability": {
            "supported": True,
            "preferred_methods": ["integrated_gradients", "attention_rollout"],
            "target_type": "similarity_score",
            "input_type": "text_pair",
            "attribution_level": "token",
            "requires_gradients": True,
            "requires_attention": True,
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": True,
        },
    },
    "roberta-base_similarity": {
        "hf_model_id": "roberta-base",
        "task_key": "sentence_similarity",
        "pipeline_tag": "sentence-similarity",
        "family": "roberta",
        "modality": "text",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["glue_stsb", "glue_mrpc"],
        "loader_template": "hf_sentence_similarity",
        "explainability": {
            "supported": True,
            "preferred_methods": ["integrated_gradients", "attention_rollout"],
            "target_type": "similarity_score",
            "input_type": "text_pair",
            "attribution_level": "token",
            "requires_gradients": True,
            "requires_attention": True,
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": True,
        },
    },
    "MiniLM_similarity": {
        "hf_model_id": "microsoft/MiniLM-L12-H384-uncased",
        "task_key": "sentence_similarity",
        "pipeline_tag": "sentence-similarity",
        "family": "MiniLM",
        "modality": "text",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["glue_stsb"],
        "loader_template": "hf_sentence_similarity",
        "explainability": {
            "supported": True,
            "preferred_methods": ["integrated_gradients", "token_saliency"],
            "target_type": "similarity_score",
            "input_type": "text_pair",
            "attribution_level": "token",
            "requires_gradients": True,
            "requires_attention": False,
            "supports_gradients": True,
            "supports_attention_rollout": False,
            "supports_token_attribution": True,
        },
    },
    "distilroberta-base_fillmask": {
        "hf_model_id": "distilroberta-base",
        "task_key": "fill_mask",
        "pipeline_tag": "fill-mask",
        "family": "roberta",
        "modality": "text",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["wikitext2", "ag_news_fillmask"],
        "loader_template": "hf_fill_mask",
        "explainability": {
            "supported": True,
            "preferred_methods": ["integrated_gradients", "attention_rollout"],
            "target_type": "masked_token",
            "input_type": "single_text",
            "attribution_level": "token",
            "requires_gradients": True,
            "requires_attention": True,
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": True,
        },
    },
    "bert-base-uncased_fillmask": {
        "hf_model_id": "bert-base-uncased",
        "task_key": "fill_mask",
        "pipeline_tag": "fill-mask",
        "family": "bert",
        "modality": "text",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["wikitext2", "ag_news_fillmask"],
        "loader_template": "hf_fill_mask",
        "explainability": {
            "supported": True,
            "preferred_methods": ["integrated_gradients", "attention_rollout"],
            "target_type": "masked_token",
            "input_type": "single_text",
            "attribution_level": "token",
            "requires_gradients": True,
            "requires_attention": True,
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": True,
        },
    },
    "distilgpt2_textgen": {
        "hf_model_id": "distilgpt2",
        "task_key": "text_generation",
        "pipeline_tag": "text-generation",
        "family": "gpt2",
        "modality": "text",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["wikitext2_lm"],
        "loader_template": "hf_causal_lm",
        "explainability": {
            "supported": True,
            "preferred_methods": ["integrated_gradients", "token_saliency"],
            "target_type": "generated_token",
            "input_type": "single_text",
            "attribution_level": "token",
            "requires_gradients": True,
            "requires_attention": False,
            "supports_gradients": True,
            "supports_attention_rollout": False,
            "supports_token_attribution": True,
        },
    },
    "gpt2_textgen": {
        "hf_model_id": "gpt2",
        "task_key": "text_generation",
        "pipeline_tag": "text-generation",
        "family": "gpt2",
        "modality": "text",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["wikitext2_lm"],
        "loader_template": "hf_causal_lm",
        "explainability": {
            "supported": True,
            "preferred_methods": ["integrated_gradients", "token_saliency"],
            "target_type": "generated_token",
            "input_type": "single_text",
            "attribution_level": "token",
            "requires_gradients": True,
            "requires_attention": False,
            "supports_gradients": True,
            "supports_attention_rollout": False,
            "supports_token_attribution": True,
        },
    },
    "flan-t5-small_text2text": {
        "hf_model_id": "google/flan-t5-small",
        "task_key": "text2text_generation",
        "pipeline_tag": "text2text-generation",
        "family": "t5",
        "modality": "text",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["cnn_dailymail"],
        "loader_template": "hf_seq2seq",
        "explainability": {
            "supported": True,
            "preferred_methods": ["integrated_gradients", "attention_rollout"],
            "target_type": "summary_token",
            "input_type": "single_text",
            "attribution_level": "token",
            "requires_gradients": True,
            "requires_attention": True,
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": True,
        },
    },
    "t5-small_text2text": {
        "hf_model_id": "t5-small",
        "task_key": "text2text_generation",
        "pipeline_tag": "text2text-generation",
        "family": "t5",
        "modality": "text",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["cnn_dailymail"],
        "loader_template": "hf_seq2seq",
        "explainability": {
            "supported": True,
            "preferred_methods": ["integrated_gradients", "attention_rollout"],
            "target_type": "summary_token",
            "input_type": "single_text",
            "attribution_level": "token",
            "requires_gradients": True,
            "requires_attention": True,
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": True,
        },
    },
        "vit-base-patch16-224_imgcls": {
        "hf_model_id": "google/vit-base-patch16-224",
        "task_key": "image_classification",
        "pipeline_tag": "image-classification",
        "family": "vit",
        "modality": "image",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["beans", "cifar10"],
        "loader_template": "auto_image_classification",
        "explainability": {
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": False,
        },
    },
    "mobilevit-small_imgcls": {
        "hf_model_id": "apple/mobilevit-small",
        "task_key": "image_classification",
        "pipeline_tag": "image-classification",
        "family": "mobilevit",
        "modality": "image",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["beans", "cifar10"],
        "loader_template": "auto_image_classification",
        "explainability": {
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": False,
        },
    },

    "detr-resnet-50_objdet": {
        "hf_model_id": "facebook/detr-resnet-50",
        "task_key": "object_detection",
        "pipeline_tag": "object-detection",
        "family": "detr",
        "modality": "image",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["coco_detection"],
        "loader_template": "auto_object_detection",
        "explainability": {
            "supports_gradients": True,
            "supports_attention_rollout": False,
            "supports_token_attribution": False,
        },
    },
    "yolos-small_objdet": {
        "hf_model_id": "hustvl/yolos-small",
        "task_key": "object_detection",
        "pipeline_tag": "object-detection",
        "family": "yolos",
        "modality": "image",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["coco_detection"],
        "loader_template": "auto_object_detection",
        "explainability": {
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": False,
        },
    },
    "rtdetr-r18vd_objdet": {
        "hf_model_id": "PekingU/rtdetr_r18vd_coco_o365",
        "task_key": "object_detection",
        "pipeline_tag": "object-detection",
        "family": "rtdetr",
        "modality": "image",
        "model_role": "task_head",
        "allowed_run_regimes": ["inference_only"],
        "dataset_keys": ["coco_detection"],
        "loader_template": "auto_object_detection",
        "explainability": {
            "supports_gradients": True,
            "supports_attention_rollout": False,
            "supports_token_attribution": False,
        },
    },

    "segformer-b0_seg": {
        "hf_model_id": "nvidia/segformer-b0-finetuned-ade-512-512",
        "task_key": "image_segmentation",
        "pipeline_tag": "image-segmentation",
        "family": "segformer",
        "modality": "image",
        "model_role": "task_head",
        "allowed_run_regimes": ["finetune_transfer", "inference_only"],
        "dataset_keys": ["scene_parse_150"],
        "loader_template": "auto_image_segmentation",
        "explainability": {
            "supports_gradients": True,
            "supports_attention_rollout": False,
            "supports_token_attribution": False,
        },
    },
    "segformer-b2_seg": {
        "hf_model_id": "nvidia/segformer-b2-finetuned-ade-512-512",
        "task_key": "image_segmentation",
        "pipeline_tag": "image-segmentation",
        "family": "segformer",
        "modality": "image",
        "model_role": "task_head",
        "allowed_run_regimes": ["inference_only"],
        "dataset_keys": ["scene_parse_150"],
        "loader_template": "auto_image_segmentation",
        "explainability": {
            "supports_gradients": True,
            "supports_attention_rollout": False,
            "supports_token_attribution": False,
        },
    },

    "blip-caption-base": {
        "hf_model_id": "Salesforce/blip-image-captioning-base",
        "task_key": "image_captioning",
        "pipeline_tag": "image-to-text",
        "family": "blip",
        "modality": "multimodal",
        "model_role": "task_head",
        "allowed_run_regimes": ["inference_only"],
        "dataset_keys": ["flickr8k_captioning"],
        "loader_template": "auto_image_to_text",
        "explainability": {
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": True,
        },
    },

    "clip-vit-base-patch32_retrieval": {
        "hf_model_id": "openai/clip-vit-base-patch32",
        "task_key": "text_image_retrieval",
        "pipeline_tag": "zero-shot-image-classification",
        "family": "clip",
        "modality": "multimodal",
        "model_role": "dual_encoder",
        "allowed_run_regimes": ["inference_only"],
        "dataset_keys": ["flickr8k_retrieval"],
        "loader_template": "auto_clip_retrieval",
        "explainability": {
            "supports_gradients": True,
            "supports_attention_rollout": False,
            "supports_token_attribution": True,
        },
    },
    "clip-vit-large-patch14_retrieval": {
        "hf_model_id": "openai/clip-vit-large-patch14",
        "task_key": "text_image_retrieval",
        "pipeline_tag": "zero-shot-image-classification",
        "family": "clip",
        "modality": "multimodal",
        "model_role": "dual_encoder",
        "allowed_run_regimes": ["inference_only"],
        "dataset_keys": ["flickr8k_retrieval"],
        "loader_template": "auto_clip_retrieval",
        "explainability": {
            "supports_gradients": True,
            "supports_attention_rollout": False,
            "supports_token_attribution": True,
        },
    },

    "blip-vqa-base": {
        "hf_model_id": "Salesforce/blip-vqa-base",
        "task_key": "visual_question_answering",
        "pipeline_tag": "visual-question-answering",
        "family": "blip",
        "modality": "multimodal",
        "model_role": "task_head",
        "allowed_run_regimes": ["inference_only"],
        "dataset_keys": ["vqav2"],
        "loader_template": "auto_vqa",
        "explainability": {
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": True,
        },
    },
    "vilt-b32-vqa": {
        "hf_model_id": "dandelin/vilt-b32-finetuned-vqa",
        "task_key": "visual_question_answering",
        "pipeline_tag": "visual-question-answering",
        "family": "vilt",
        "modality": "multimodal",
        "model_role": "task_head",
        "allowed_run_regimes": ["inference_only"],
        "dataset_keys": ["vqav2"],
        "loader_template": "auto_vqa",
        "explainability": {
            "supports_gradients": True,
            "supports_attention_rollout": True,
            "supports_token_attribution": True,
        },
    },
}
